# Generated by Django 3.0.5 on 2020-04-25 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Name', models.CharField(max_length=30)),
                ('Password', models.CharField(max_length=20)),
                ('Role', models.CharField(max_length=20)),
                ('First_Name', models.CharField(max_length=50)),
                ('Last_Name', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=20)),
                ('Phone_Number', models.IntegerField()),
                ('Student_Id', models.IntegerField()),
                ('Address', models.CharField(max_length=50)),
                ('Pin_Code', models.IntegerField()),
            ],
        ),
    ]
